# Generated by Django 2.2.19 on 2021-04-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sent_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='messageaction',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messageaction',
            name='profile',
        ),
        migrations.DeleteModel(
            name='ForwardedMessage',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageAction',
        ),
    ]
